(import (rnrs)
        (srfi :78)
        (rbtrees))

(let ([rb (make-rb-trees)])
  (check (rb-trees? rb) => #t)
  (check (check-rb rb) => #t)
  (rb-set! rb 1 'val1)
  (check (check-rb rb) => #t)
  (rb-set! rb 2 'val2)
 (rb-set! rb 5 'val5)
   (check (check-rb rb) => #t)
   (rb-set! rb 3 'val3)
 (check (check-rb rb) => #t)
 (rb-set! rb 4 'val4)
(check (check-rb rb) => #t)
  (let ([port (open-output-file "rb-trees.dot")])
    (rb->dot rb port)
    (close-port port)))

(check-report)
